a = input('nhap gia tri')
ds = a.split(",")
ds1 = tuple(ds)
print(ds)
print(ds1)
###############################################
values=input("Nhập vào các giá trị:")
l=values.split(",")
t=tuple(l)
print (l)
print (t)